language: python
python:
- 3.6
env:
- DJANGO_VERSION=1.11.4
install:
- pip install -q Django==$DJANGO_VERSION
- pip install -r requirements.txt
before_script:
- python3 manage.py makemigrations
- python3 manage.py migrate
script:
- python3 manage.py test
deploy:
  provider: heroku
  api_key:
    secure: bjqtmsEduX6bE9PfSnEQ59k9uJbuBQMKpQVN2Izf3W5BXfT1ADGuz5RoMb6IqJgc8XMDJ82MURIBJdyrJkhuVrWyB1S4FoF0hVFdfiH+541tapA5bBRiGvotda0IbW8+20D1yJnBOu9wMK8d/xr9kTFZj8aPAb2JDsI7MakRNGiQCXMFb9gZvp0EYahU9ias8wGKCQ/hRLzDhzRhXqo4/idHM5OxwLKmgjwcOmv99sZpDpXGSJ4/evuUQ005dx1nrLowgWxmnBMPRPB8yIWWgriwsQuoNDcx+N2EgRP9N6CPM5L333SOP1cVryNG1IoahrS8O2GulkOFT9Od3c21WRGx7IGRQeT6tRR5CJixxuvwWQKYvetgaecivvDARq6EtvRYZFQsnUEOUAn9j6zAVbqlYb6dbvO4xYQ8YP+vCRWQxBjs8YPqInYi+n7/PQWBdG+FD12VOPH/kZ7JsBu9Vnd8KRKYnln0nxRZNMv+Er+8OaheO5YOkNhloymhhqgUHiqqVtHfmnH7F7LCsBicH0GNZP2SpGSZquSm8+jl+eLjr6L+NHNGFWg2DQXwtyxrl8JBYXrObEymAjMRUweLD412p3VPEa3Fi5OvWuAlKdW5PSRMQIXVNiAlmYS7zxuCSPJfpS+nOHwACadvdNzZITpKZTL5Kh2phqhaF3tsmv0=
  app: gcs01-mateusdemorais-travis
