language: python

python: 
    - 3.6

env:
    - DJANGO_VERSION=1.11.4

install: 
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements.txt

before_script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate

script:
    - python3 manage.py test

deploy:
  provider: heroku
  api_key:
    secure: 8eb6e3ce051d89d6271da2fe029170ee1831855b
  app: gcs01-mateusdemorais-travis
